### ISSUE TITLE
Non-DMG version of files?

### ISSUE THREAD

**Issue by fuchsia-spinel** [jaredplumb/Dragon-Alpha#1]
Can we get a version of the files that aren't locked in a DMG? I was able to extract most of them on Windows, but the TMPL and Data files are saying they're 0 bytes. This isn't the first time I've had something like this happen when extracting Mac images.

**Comment by jaredplumb** [comment]
A DMG is not a locked file but a disk image, which remains a commonly used file type today. If you're not familiar with these types of files, it might be helpful to gain more understanding before working on updating this project. Many files in Dragon Alpha contain a resource fork, which is preserved within the disk image. Before removing the DMG, the system would need to be updated, or else the project may not function as expected.

**Comment by fuchsia-spinel** [comment]
@jaredplumb Sorry, my terminology wasn't great. I didn't mean "locked" in a literal sense, more in the sense that some of the files are stuck in a specific storage format that I can't access properly on my Windows PC. I just meant that I would appreciate it being reuploaded as flat files. The resource forks (which I was unsure if that was the issue) aren't compatible with non-Mac systems. I was hoping to look into making a cross-platform version, but it's difficult when the main plugin configuration files are extracting to 0 bytes.

**Comment by jaredplumb** [comment]
@fuchsia-spinel The main issue lies with the resource forks themselves, as they contain all of the game data. Uploading them without the resource forks would require significant rework of the codebase to support a different file format. Ideally, I would prefer using JSON files in a modern context, but this is the key challenge in updating the game.

**Comment by fuchsia-spinel** [comment]
@jaredplumb If you (or someone else with a Mac) can do it, Jorio's rsrcdump ( https://github.com/jorio/rsrcdump ) should be able to automatically convert them to JSONs. I've yet to be able to do it on Windows. My emulators either don't recognize the disk or are suddenly having issues I can't seem to debug.

> Ideally, I would prefer using JSON files in a modern context, but this is the key challenge in updating the game.

This isn't a concern to me. I just need the data. I played this game a *long* time ago now and was interested in porting it to a new engine entirely, since the existing code relies so heavily on Mac-specific libraries anyways.
